### ISSUE TITLE
Rectification sur algo optim

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#10]
Dans les contraintes sur les faces fixes, enlever la variation autorisée de 500MW (faces 0 -1 0 et 0 1 0) autour de la variable de_min/de_max

**Comment by TitouanRobert** [comment]
Du coup je peux remplacer les deux contraintes sur le de_min par une seule? (un ==). La j'ai de_min>= valeur et  de_min<= valeur

**Comment by MarionLi0** [comment]
Oui!

**Comment by TitouanRobert** [comment]
C'est fait
