### ISSUE TITLE
Correction bindingconstraints.ini

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#13]
1. Changer dans toutes les fonctions et inputs les noms des constraintes FB en ajoutant _fb
(FB01_fb)
2. Lors de l'écriture du fichier, supprimer les contraintes se terminant par _fb ou _FB qui ne font pas partie de l'étude (comme fb_de_FB qui n'existe pas dans la nouvelle modélisation)

**Comment by TitouanRobert** [comment]
J'ai ajouté aussi _fb dans les identifiants (pour garder la cohérence identifiant / nom), je te laisse tester et fermer l'issue si c'est ok pour toi
