### ISSUE TITLE
initFlowbased : initalizing binding constraints

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#14]
`initFlowbased `must create the new binding constraints which will - later - be used to model the flow-based domains, i.e. `initFlowbased ` must : 

1. Update the `bindingconstraint.ini` file with the new constraints FBXX_fr
2. create the txt files related to the new constraints (`FBXX_fb.txt`) -> **this feature is not yet implemented**

If those two conditions are not fulfilled, ANTARES returns an error when opening the study.

Note that the txt files (`FBXX_fb.txt`) can be empty.

**Comment by TitouanRobert** [comment]
It's done, i let you close the issue if it's ok.

**Comment by baptsegu** [comment]
It's ok ! Thank you
