### ISSUE TITLE
Launch ANTARES in parallel with V6

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#15]
ANTARES V6 offers the possibility to launch ANTARES in parallel.

- Add an argument in `runSimulationFB()` to decide weither or not the simulations (for each climate years) should be run in parallel
- Adapt the system command to ANTARES depending on the value of this argument.

**Comment by baptsegu** [comment]
Parallel mode can be set when running ANTARES in system command with optionnal `--parallel ` argument.

Note that this argument can be used only if ANTARES solver version is above  6.0.0 (include control on ANTARES version).


![image](https://user-images.githubusercontent.com/23483145/26936903-3daeb73e-4c70-11e7-8639-28e8f940d326.png)

**Comment by TitouanRobert** [comment]
It's done
