### ISSUE TITLE
Do not export all functions

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#16]
To clarify the help page of the package, export only the function which will be directly used by the ANTARES's users : 
* `addChroniquesFile`
* `adqPatch`
* `computeFB`
* `getAvailableModel`
* `getSolverAntares`
* `getVertices`
* `initFlowBased`
* `plotFB `or `graphFlowBased2D `(see below)
* `runAppError`
* `runSimulationFB`
* `setFlowbasedPath`
* `setSolverAntares`

`plotFB ` and `graphFlowBased2D ` : what is the difference between those two functions ? Which one should be exported ?

**Comment by TitouanRobert** [comment]
Les fonctions que j'ai conservées après tri : 

- addChroniquesFile
- adqPatch
- computeFB
- fbOptions
- generateRaportFb
- getAvailableModel
- getSolverAntares
- initFlowBased
- plotFB
- runAppError
- runSimulationFB
- setFlowbasedPath
- setSolverAntares
- writeIni

**Comment by bthieurmel** [comment]
@baptsegu : do you want to keep the man page of unexported functions ? If not @TitouanRobert  have to add ``@noRd`` in R code.

**Comment by bthieurmel** [comment]
Maybe have to rename ``addChroniquesFile`` in ``addChroniclesFile`` or other ?

**Comment by baptsegu** [comment]
Concerning the man page of the unexported functions, I would like to : 
- not see the function in the general help of the package (`help(package = "antaresFlowbased")`), but
- have a man page if I'm specifically looking for the help of an unexported function (`??antaresFlowbased:::askProblemeMat`)

Concerning the names : 
`addChroniquesFiles `could be changed in `addTSFile `(for Time Series)
And OK for `generateReportFB` instead of `generateRaportFb`

**Comment by bthieurmel** [comment]
I think it's not possible to do that for the man. If we decide to create a man page, it will be visible in R using ``?`` and in the global help. Have to see if there is an option....

**Comment by baptsegu** [comment]
In that case, you can use `@noRd`.
