### ISSUE TITLE
adqPatch mcYear & pre_filter

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#19]
Ajouter la variable mcYear (= "all" par défaut) permettant manuellement de choisir les années sur lesquelles lancer l'adequacy patch, cette variable se répercute donc aussi dans les readAntares

Pour diminuer le temps de calcul?
Ajouter un paramètre pre_filter (par défaut = FALSE). Si TRUE:
Avant de lancer le readAntares, faire un readAntares sur les années (timestep = "annual") et filtrer les années avec LOLD>0. Ne charger ensuite que ces années et leur appliquer l'adequacy patch (les autres n'ont jamais d'heures de défaillance, pas la peine de les charger)

**Comment by baptsegu** [comment]
@MarionLi0  : cette issue est-elle toujours d'actualité ?

**Comment by MarionLi0** [comment]
Changer le message écrit dans la console si l'adequacy patch n'est pas utilisé car pas de défaillance  = LOLD ==0 tout le temps (remplacer "no row concerned by adq patch")

> No loss of load in this simulation, the adequacy patch is not used

**Comment by TitouanRobert** [comment]
Ok, j'ai une seconde fois le message : No row concern by adq patch (si on a de la défaillance mais pas de marges) je change celui la aussi?

**Comment by MarionLi0** [comment]
bug sur pre_filter, message d'erreur non clair 
![image](https://user-images.githubusercontent.com/24607174/36483777-5fe8345c-1717-11e8-817c-2927a11c849f.png)

**Comment by MarionLi0** [comment]
Second message: 

> No loss of load in several countries at the same time (and no transfer), the adequacy patch is not used

**Comment by MarionLi0** [comment]
SI on combine le pre_filter avec une sélection d'années sans défaillance, l'erreur n'est pas claire
![image](https://user-images.githubusercontent.com/24607174/36586858-7fda3a54-1883-11e8-92ba-06367bfddb3b.png)
Peux tu plutôt mettre un message similaire aux autres ("No loss of load in this selection of mcYear : the adequacy patch is not used")?

**Comment by MarionLi0** [comment]
J'ai ajouté un s : No loss of load in this selection of mcYears : the adequacy patch is not used
