### ISSUE TITLE
Warning adequacy patch

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#20]
Warning déjà en place: si LOLD = 1 et DTG MRG>0
Dans le cas où strategic_reserve non NULL, ça ne devrait plus exister: ce warning peut être supprimé.
Dans le cas où strategic_reserve = NULL, on reste dans la situation précédente, où ce warning peut être actif.

Conclusion: si ça prend du temps et qu'il peut être omis facilement dans juste un des cas, à faire, sinon ne rien changer

**Comment by baptsegu** [comment]
@MarionLi0  : cette issue est-elle toujours d'actualité ?

**Comment by TitouanRobert** [comment]
Je supprimes le test suivant : 
`
test_that("checks warning when strategic reserves in the country", {
  expect_warning(.applyAdq(opts = opts, dataNoStrat_ini),
                 "mcYear : 589 timeId : 2017-12-07 17:00:00 de has LOLD = 1 but DTG MRG>0, adequacy patch not applied")
  expect_warning(.applyAdq(opts = opts, dataNoStrat_ini),
                 "mcYear : 589 timeId : 2017-12-11 17:00:00 de has LOLD = 1 but DTG MRG>0, adequacy patch not applied")
})
`

Dans ce test -> strategic_reserve = NULL. Il n'est donc plus d'actualité avec la nouvelle version.

**Comment by MarionLi0** [comment]
Non ne le supprime pas!!! Ce test concerne un autre cas, à savoir que se passe-t-il si les réserves stratégiques sont à l'intérieur du noeud et pas dans un noeud virtuel. Dans ce cas là, on ne traite pas le problème et on sort le message de warning!

**Comment by TitouanRobert** [comment]
C'est ma faute! J'avais mal lu. C'est bon et ça fonctionne.
