### ISSUE TITLE
add in testStudy() a test with adequacy patch

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#21]
Keep the same test (check that all net positions **before adequacy patch** are included in the domains)
+ run adequacy patch on output
+ check that all net positions **after adequacy patch** are included in the domains.

**Comment by MarionLi0** [comment]
Test adq patch:
+ for each timeId:
`sum(UNSP. ENRG)` (before) <= `sum(UNSP. ENRG)` (after)
+ for each area and timeId : 
`DTG MRG + BALANCE - UNSP. ENRG` (before (readAntares)) =  `DTG MRG + BALANCE - UNSP. ENRG` (after (adqPatch))
+ for each timeId:
`sum(DTG MRG)` (before) <= `sum(DTG MRG)` (after)

**Comment by MarionLi0** [comment]
Test adq patch with additionnal constraint:
`BALANCE`, `UNSP. ENRG`, `LOLD`, `DTG MRG` unchanged compared to `adqPatch` with no additionnal constraint

**Comment by MarionLi0** [comment]
Test adq patch with strategic reserve:
+ `additionnalSR`>=0
+ if adqPatch not applied (LOLD all =0), `additionnalSR` = 0
+ for countries with no sr, `additionnalSR` = 0

+` BALANCE`, `DTG MRG` unchanged compared to `adqPatch` without strategic reserve
+ `UNSP. ENRG = max( 0 , UNSP.ENRG(without_sr) - initial DTG MRG(strategic reserve)`
+ if `UNSP. ENRG` = 0, `LOLD` = 0

+ for countries with sr, `additionnalSR = UNSP.ENRG (without_sr) - UNSP.ENRG `
+ for countries with sr, `additionnalSR `<= `initial DTG MRG(strategic reserve)`

**Comment by MarionLi0** [comment]
Test adq patch links: calculation of CWE NP
+ if country has `LOLD==1`, `NP<=0`

**Comment by TitouanRobert** [comment]
RAF : 

Après application ADQ : 

Test adq patch with strategic reserve:

    additionnalSR>=0

    if adqPatch not applied (LOLD all =0), additionnalSR = 0

    for countries with no sr, additionnalSR = 0

    BALANCE, DTG MRG unchanged compared to adqPatch without strategic reserve

    UNSP. ENRG = max( 0 , UNSP.ENRG(without_sr) - initial DTG MRG(strategic reserve)

    if UNSP. ENRG = 0, LOLD = 0

    for countries with sr, additionnalSR = UNSP.ENRG (without_sr) - UNSP.ENRG

    for countries with sr, additionnalSR<= initial DTG MRG(strategic reserve)

**Comment by TitouanRobert** [comment]
Pour ce test j'ai exclu le time id 589 (l'adq n'est pas appliqué a ce time id)
