### ISSUE TITLE
adqPatch : add agument select

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#22]
Argument `select `similar to the one of the function `antaresRead::readAntares()`.

Default value is a **new alias** `adqPatch` equal to `c("LOLD", "UNSP. ENRG", "DTG MRG",  "BALANCE", "FLOW LIN.")`.

Other value can be used (cf. `readAntares()` help) to select additional columns which are not required by the adequacy patch but which could be usefull for the user specific purposes.

The columns required for the adequacy Patch should be included in all cases. I.e : `select = unique(select, adqPatch)`.

**Comment by TitouanRobert** [comment]
Done

**Comment by MarionLi0** [comment]
3 issues:
- if default value for select, the resulting tables should display the areas and the links with "LOLD", "UNSP. ENRG", "DTG MRG", "BALANCE", "FLOW LIN." values
- if select="COAL" (example), the column must be added to the initial table
- in all cases, the column ipn must be removed from the output

**Comment by MarionLi0** [comment]
To add:
if select = "all", then all variables are displayed
