### ISSUE TITLE
adqPatch : add column additional_sr

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#24]
In the output of `adqPatch()`, replace column `strategicMargin` by `additionalSR`.

`additionalSR = strategicMargin(before adqPatch) - strategicMargin(after adqPatch) `

**Comment by TitouanRobert** [comment]
A new column is add : additionalSR = `DTG MRG` - strategicMargin. Supress of column strategicMargin in ouput$areas,

**Comment by MarionLi0** [comment]
additionalSR = DTG MRG - strategicMargin : **wrong expression**

**Comment by TitouanRobert** [comment]
Check with issue 21
