### ISSUE TITLE
adqPatch : return clear error when strategic_reserve_de/be are not areas of the study

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#25]

**Comment by TitouanRobert** [comment]
Add this message : Error in adqPatch(strategic_reserve_de = "lu_de", strategic_reserve_be = "lu_b") : 
  Somes strategic_reserve_be are not in areas

**Comment by baptsegu** [comment]
Change the message to : ```
Error in adqPatch(strategic_reserve_de = "lu_de", strategic_reserve_be = "lu_b") :
area "lu_b" does not exist
```

**Comment by TitouanRobert** [comment]
Ok, it's done

**Comment by MarionLi0** [comment]
@baptsegu  Est ce qu'on n'interdirait pas le même nom (donc même noeud) utilisé pour les 2 pays?

**Comment by baptsegu** [comment]
Si, ça me semble pertinent.

**Comment by MarionLi0** [comment]
@TitouanRobert 
Il faudrait ajouter un contrôle pour interdire que les deux réserves stratégiques soient associées au même nom.
Si même nom renseigné par l'utilisateur, alors ERROR : strategic_reserve_be and strategic_reserve_de must have different names

**Comment by MarionLi0** [comment]
Parfait
