### ISSUE TITLE
Mandatory Results filtering option at "None" for flow based simulation

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#28]
If Results filtering = Custom:

>runSimulationFB(simulationName = "test") 

Error in .errorTest(upGenIni, verbose, "Write of generaldata") : 
  Write of generaldata : Error in modifyGeneralSetting(generaldataIniPatch) : 
  Param Output profile : Results filtering is Custom, he must be None for flowbased simulation

Change mandatory "None" into a check of the existence in the "Custom" option of all the necessary outputs?

**Comment by baptsegu** [comment]
When "custom" is used : 
 * All mc-all filter should **automatically** be applied for mc-ind. For example, if the user asked for weekly results for a specific area in mc-all, the function should force the weekly results for this area in mc_ind in order to be able to perform the aggregation afterward.
 * The aggregation should be applied only on the results which are asked in mc-all.

**Comment by baptsegu** [comment]
Filter on areas in : 
`input/areas/areaName/optimization.ini`

Filter on links in : 
`input/links/areaName1/properties.ini`

**Comment by TitouanRobert** [comment]
Do you want to keep optimization.ini and properties.ini users files and give back them when simulation is finish?

**Comment by baptsegu** [comment]
Yeah. It is a great idea :)

**Comment by TitouanRobert** [comment]
How i can recupe areas filtered in mc-ind (before re-agregate)?

**Comment by baptsegu** [comment]
Pour les zones qui sont conservées par le filtre en mc-ind, les outputs des mc-ind doivent être copiés dans un dossier commun (comme c'est le cas actuellement).

Les informations sur les filtres sont donnés dans 
`input/areas/areaName/optimization.ini`

**Comment by TitouanRobert** [comment]
C'est fait. Les fichiers utilisateurs sont conservés dans user/tempfile et ils sont restaurés à la fin de l’agrégation.

**Comment by MarionLi0** [comment]
![image](https://user-images.githubusercontent.com/24607174/31935538-65bf6c9a-b8af-11e7-9db2-234d0356ccd2.png)

+ English : "changed" and "removed"
+ ERROR at computation

**Comment by baptsegu** [comment]
Tous les cas suivant doivent être gérés par la nouvelle fonctionnalité.


Quand on a une zone pour laquelle seuls les mc-all sont demandés :  
* **ne fonctionne pas** 
* `runSimulationFB()` doit forcer l'écriture des mc-inds pour cette zone afin que l'agrégation soit possible.
* après agrégation, les mc-ind de cette zones doivent être supprimés


Quand on a un lien pour lequel seuls les mc-all sont demandés : 
* **ne fonctionne pas** 
* `runSimulationFB` doit forcer l'écriture des mc-inds pour ce lien afin que l'agrégation soit possible.
* après agrégation, les mc-ind de ce lien doivent être supprimés

Quand on a une zone pour laquelle aucun output n'est demandé
* **ne fonctionne pas**
* `runSimulationFB()` ne doit pas écrire les outputs pour cette zone
* l'agrégation du mc-all ne doit pas être faite pour cette zone

Quand on a lien pour lequel aucun output n'est demandé
* **ne fonctionne pas**
* `runSimulationFB()` ne doit pas écrire les outputs pour ce lien
* l'agrégation du mc-all ne doit pas être faite pour ce lien

Quand on a une zone pour laquelle seuls les mc-ind sont demandés
* **ne fonctionne pas**
* `runSimulationFB()` ne doit pas écrire les outputs pour cette zone
* l'agrégation du mc-all ne doit pas être faite pour cette zone

Quand on a un lien pour lequel seuls les mc-ind sont demandés
* **non testé**
* `runSimulationFB()` ne doit pas écrire les outputs pour ce lien
* l'agrégation du mc-all ne doit pas être faite pour ce lien

Les combinaisons ci-dessus sont également à tester avec seulement une partie des agrégations temporelles demandés pour le lien/la zone, les mcInd/mcAll (par exemple, annual seulement)
* **non testé**

Quand filtering options est à `TRUE` mais qu'en pratique tous les outputs sont demandés sur toute les zones et tous les liens : 
* **ne fonctionne pas**
* dans ce cas, la fonction `runSimulationFB()` doit fonctionner comme avant : tous les outputs doivent être écrits

**Comment by TitouanRobert** [comment]
Ne concerne plus la nouvelle version.
