### ISSUE TITLE
adqPatch() : handle the extra constraints

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#29]
The `adqPatch()` should apply on contraints (FBXX_fb) which are included in **both** (i.e intersection of) the files : 
* `weight.txt`
* `secondMember.txt`

In some exceptionnal uses, the user might want to add additional "stochastic" constraints and handle them manually with` secondMember.txt`. Those new constraints are not flow-based constraints and shouldn't be considered by` adqPatch()`

**Comment by TitouanRobert** [comment]
Code added. Cat messages are print if somes constraints are excludes.
````
  contraintsExcludes <- setdiff(unique(secondM$Name),b36p$name)
  if(length(contraintsExcludes) > 0){
    cat("Somes contraints are excludes because they are not in second_member and in weight")
    cat(paste0("contraints exclude(s) : ", paste(contraintsExcludes , collapse = ", ")))
    secondM <- secondM[!Name%in%contraintsExcludes]
    b36p <- b36p[!name%in%contraintsExcludes]
  }
````

**Comment by MarionLi0** [comment]
Message:
Ignored constraint(s): ""
They are not described in the two flow-based files second_member.txt and weight.txt.
