### ISSUE TITLE
Ajouter un argument mcYears dans runSimulation

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#3]
qui définit une "playlist" des années à simuler.

Avec comme valeur par défaut "all" : dans ce cas, on simule autant d'années qu'il y en a renseignées dans scenario.txt.

Sinon, on ne simule que les identifiants des années renseignées dans l'argument mcYears. Par exemple, il y a actuellement 5*200 années renseignées dans le fichier scenario.txt, un mcYears = 1:200 ne simulerait que les 200 premières.

**Comment by TitouanRobert** [comment]
J'ai ajouté un argument qui exclus des mcYears, (MCyearsExcludes). Dis moi si tu préfères que je laisse MCyearsExcludes ou que je fasses un argument mcYears (l'inverse de MCyearsExcludes).

**Comment by baptsegu** [comment]
Je préfère la deuxième option, un argument mcYears (identifiant des mcYears à inclure).

Cela permettra de rester dans la même logique que la playlist ANTARES et les autres fonctions de François.

**Comment by TitouanRobert** [comment]
Ok c'est fait (argument mcYears)
