### ISSUE TITLE
initFlowBased() : add information on creation of scenario.txt

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#30]
add a parameter named "scenarios", a vector with default value `rep(1:200, times = 5)`

**Comment by TitouanRobert** [comment]
Done argument scenarios add, 

Documentation : 
#' @param scenarios\code{numeric} scenarios use for write scenario.txt.

Default : 

scenarios = rep(1:200, times = 5)

**Comment by baptsegu** [comment]
Documentation :
#' @Param scenarios\code{numeric} vector of time series identifier. The size of the vector corresponds to the number of Monte-Carlo years which must be simulated. Each value corresponds to the identifier of the flow-based time series which will be used for each Monte-Carlo year. This vector is used to write the file scenario.txt.

**Comment by MarionLi0** [comment]
Test ok, doc to fill
