### ISSUE TITLE
Unknown dependancies

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#32]
Necessity to install additionnal packages (not in the description):

![image](https://user-images.githubusercontent.com/24607174/32374322-67c382d8-c09d-11e7-8f6a-cc851edfd796.png)

**Comment by MarionLi0** [comment]
![image](https://user-images.githubusercontent.com/24607174/32374304-500e43da-c09d-11e7-9ce0-50c3207a85e5.png)

**Comment by baptsegu** [comment]
@MarionLi0  : cette issue était pour le package `flowBasedClustering`, non ? 

Si oui, l'issue a été corrigée et peut être fermée.
