### ISSUE TITLE
new function() : vizualise net position and flow-based domains

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#33]
Trace sur un graphe les positions nettes ainsi que le domaine flow-based d'un typical day et d'une heure donnée.

Similaire à ce qui est fait avec la fonction de test `plotTest()`.

**Comment by TitouanRobert** [comment]
C'est la fonction positionViz, le nom est pas super si vous avez de meilleurs idées.

**Comment by MarionLi0** [comment]
![image](https://user-images.githubusercontent.com/24607174/36590714-d70d368a-188f-11e8-8393-a58ff286af17.png)
C'est définitivement impossible de faire quelque chose pour ça?

**Comment by MarionLi0** [comment]
positionFBViz ?

**Comment by MarionLi0** [comment]
Lorsque l'on passe la souris sur un point, on voit ses coordonnées dans un encadré, est il possible d'ajouter à cet encadré la date? (jour-mois)

**Comment by MarionLi0** [comment]
Description de la fonction:
Mettre dans la description de l'heure que cela va de 0 à 23 et pas de 1 à 24. A faire pour toutes les fonctions de plot...

**Comment by MarionLi0** [comment]
Arguments de la fonction:
On est obligé de créer opts, ne peut-on pas le lier à l'étude que l'on a chargé avec setSimulationPath juste avant? = créer un default
![image](https://user-images.githubusercontent.com/24607174/36596684-c84edaec-18a6-11e8-9376-28eb4642c73d.png)

**Comment by baptsegu** [comment]
plotNetPositionFB

**Comment by MarionLi0** [comment]
Attention, les modifs en cours font bugger l'application shiny et la fonction, notamment par rapport aux arguments ctry/country

**Comment by baptsegu** [comment]
Un problème de dépendance avec magrittr ou piper

```
positionViz( 
+             data = dta,
+             dayType = 1, hour = c(9, 19), 
+             country1 = "BE", country2 = "FR")
Error in g %>% plot() : could not find function "%>%"
```

**Comment by baptsegu** [comment]
Remplacer : 
```
Error in positionViz(data = dta, dayType = 1:12, hour = 0:23, country1 = "BE",  : 
  You try to draw 62944 points but you can't draw more than 10000 points. You can change this limit with nbMaxPt argument but be carefull, your graph can be impossible to draw if you have soo much points.
```
Par 

```
Error in positionViz(data = dta, dayType = 1:12, hour = 0:23, country1 = "BE",  : 
The graph contains 62944 points while the maximum limit is of 10000 points. This limit can be changed with nbMaxPt - but if it is too high possible visualisation problems could occur. 
```

**Comment by baptsegu** [comment]
Comment gères-tu le système de couleur ? Pourrait-on facilement proposer d'autres alternatives ?

**Comment by baptsegu** [comment]
Préciser dans l'aide le format d'heure utilisé (0->23).

Autrement ça marche bien ;)

**Comment by TitouanRobert** [comment]
Ajout de la possibilité de voir les points avant et après ADQ.

Ajout des test suivants : 
En stop: 
country1 et country2 in c("DE", "BE", "FR", "NL")

le tableau data contient bien les éléments areas et links

Les heures sont bien entre 0 et 23 (ou all)
Les dayType sont bien tous dans domaines$dayType (ou all)

en warning : 
data est un antaresDataList

**Comment by MarionLi0** [comment]
![image](https://user-images.githubusercontent.com/24607174/37353503-c40847d8-26df-11e8-8a8a-c6476e02a6b8.png)
Message d'erreur plus clair? 
This selection of typical day does not appear in the simulation data. Choose dayType = "all"

**Comment by MarionLi0** [comment]
Voici un exemple de fichier downloadé, pourrait-on avoir de la doc ou une explication sur les colonnes? Les noms ne sont pas super clairs, j'ai du mal à comprendre ce qui correspond à quoi
[test.xlsx](https://github.com/rte-antares-rpackage/antaresFlowbased/files/1807711/test.xlsx)

**Comment by MarionLi0** [comment]
![image](https://user-images.githubusercontent.com/24607174/37355094-6f0c95be-26e3-11e8-9889-617fc2561cfc.png)

Changer les noms des arguments et leur description, peu clair
- drawNoAdqPoints -> drawBeforeAdqPositions, description: boolean, draw net positions without/before adequacy patch, default TRUE
- drawAdqPoints -> drawAdqPositions, description: boolean, draw net positions after adequacy patch, default TRUE

**Comment by TitouanRobert** [comment]
Pour le message d'erreur, il s'affiche uniquement si tous les domaines sont vides et si filteringEmptyDomains = TRUE

**Comment by MarionLi0** [comment]
ça marche mais ce message s'affiche également dans un autre cas: si je demande un affichage de seulement les points après adq par exemple alors que le calcul n'a pas été fait (dta avec seulement les données avant adq)
![image](https://user-images.githubusercontent.com/24607174/37494849-ec360840-28aa-11e8-8808-1acc95983cde.png)
Est ce possible de séparer ce cas? -> This type of positions does not appear in the simulation data.

**Comment by TitouanRobert** [comment]
Ajout du contrôle suivant (et de son opposé): 

  if( drawPositionsBeforeAdqP & !drawPositionsAdqP ){
    if(!all(c("BALANCE", "UNSP. ENRG", "LOLD", "DTG MRG")%in%names(dta$areas))){
      stop("This type of positions does not appear in the simulation data.")
    }
  }

**Comment by TitouanRobert** [comment]
Fait
