### ISSUE TITLE
New function initFlowBased()

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#37]
Change the function to adapt to the new version of Antares.

Name : `initFlowBased()`

Arguments : 
- `fbModel` : flow-based model, alias of one model saved in the data of the package or directory (ou opts_fb -> **à discuter**)
- `scenarios `: vector of flow-based time series for Antares's scenarion builder (default = rep(1:200, times = 5))
- `opts` : as returned by antaresRead::setSimulationPath()

**Comment by baptsegu** [comment]
Contenu de la fonction : 

- Vérifier que la version Antares de l'étude est >= 6.1, sinon retourner l'erreur : `Flow-based modelling can only be used on studies whose Antares version if 6.1 or more`.

- Vérifier que les séries temporelles des clusters thermique sont en `ready-made` (i.e. dans le fichier settings/generaldata.ini, thermal **NE** doit **PAS** être après le `generate =`)
Si ce n'est pas le cas, retourner l'erreur `Flow-based modelling can only be used if thermal time-series are ready-made`

- Vérifier que le dossier `fbModel` contient bien les 4 fichiers nécessaires à la modélisation du flow-based. `scenario.txt`, `second_member.txt`, `ts.txt` et `weight.txt`. Sinon, retourner l'erreur `Flow-based model does not contain all necessary input files, scenario.txt, second_member.txt, ts.txt and weight.txt (%fbModel)`

Dans l'étude Antares renseignée dans `opts`

- Si elles existent, supprimer les contraintes `..._fb`
- S'il existe, supprimer le nœud `model_description_fb`
- Créer un nœud `model_description_fb`, qui n'appartient qu'à la carte `ALL`
- Pour chaque contrainte flow-based (i.e. chaque ligne `x` de `weight.txt`)

1. Créer un cluster thermique dans le noeud `model_description_fb`
Nom du cluster : `weight$name[x]` _fb (exemple : `FB01_fb`)
Unit : 1
Group : other
Nominal capacity : `max(second_memeber[name == weight$name[x], vect_b])`
All costs : 0
Min Gen Modulation : `rep(1, 8760)`
Time series : matrice des second membres.
La matrice contient autant de colonnes qu'il y a de séries temporelles renseignées dans `ts.txt`
Pour chaque colonne, chaque élément de ts.txt (identifiant des jours type) est décomposé en les 24 second membre du jour type associé de la contrainte `weight$name[x]` décrit dans `second_member.txt` (un pour chaque heure).
La matrice contient donc au final 8760 lignes et 200 colonnes.

2. Créer une contrainte couplante
Nom de la contrainte  : `weight$name[x]` _fb (exemple : `FB01_fb`)
weight.link : comme avant (décomposition des poids sur les liens de<->nl<->be<->fr)
weight.cluster.FBXX_fb : -1

- Mettre à jour le scenario builder
L'ordre de sélection des time series des groupes thermiques FBXX_fb doitt correspondre au fichier `scenario.txt`

**Comment by TitouanRobert** [comment]
Reste à faire :

    Vérifier que les séries temporelles des clusters thermique sont en ready-made (i.e. dans le fichier settings/generaldata.ini, thermal NE doit PAS être après le generate =)
    Si ce n'est pas le cas, retourner l'erreur Flow-based modelling can only be used if thermal time-series are ready-made

**Comment by MarionLi0** [comment]
J'ai une erreur : 
 Error in list.files(fbModel) : invalid 'path' argument 

Et ce que j'utilise un des modèles présents ou que je choisisse un path

**Comment by TitouanRobert** [comment]
C'est corrigé. Pour le reste à faire c'est bon c'est fait.

**Comment by TitouanRobert** [comment]
J'ai ajouté le transfert des fichiers suivants : 
weight.txt
second_member.txt
ts.txt

Ils sont maintenant automatiquement ajouté au fichier /user/flowbased de l'étude antares.

J'ai aussi ajouté le fichier domainesFB.RDS au dossier /user/flowbased , je penses que cela simplifiera l'utilisation de fonction comme positionViz (qui n'auras plus besoin que du chemin de l'étude), qu'en pensez vous ?

Une autre question, n'as t'on pas un possible problème de versionning des inputs? Si un utilisateur lance un premier initFlowBased, lance des simulations, relance un second initFlowBased et relance d'autres simulations, les inputs dans /user/flowbased ne correspondent plus aux premières simulations.

**Comment by MarionLi0** [comment]
Je n'arrive toujours pas à lancer cette fonction, mais j'ai une nouvelle erreur:
initFlowBased()
Error in if (file.size(path) == 0) { : 
  missing value where TRUE/FALSE needed

De plus, que représente le paramètre controlAntares ? la description dit juste boolean for test

**Comment by baptsegu** [comment]
> Une autre question, n'as t'on pas un possible problème de versionning des inputs? Si un utilisateur lance un premier initFlowBased, lance des simulations, relance un second initFlowBased et relance d'autres simulations, les inputs dans /user/flowbased ne correspondent plus aux premières simulations.

Si, mais ce sera également le cas si on va lire les time-series des clusters thermiques virtuels.
On a le même problème avec l'argument `thermalAvailabilites `de `antaresRead`. Dans ce cas là, on utilise le warning suivant : 
`Time series of thermal availability have not been stored in output. Time series stored in input will be used, but the result may be wrong if they have changed since the simulation has been run.`

On peut faire la même chose avec la fonction de visu : 
`Flow based model stored in the folder user/flowbased of the Antares study will be used, but the results may be wrong if the model have changed since the simulation has been run.`

**Comment by baptsegu** [comment]
De mon coté,  j'ai l'erreur suivante :  
```
> initFlowBased()
Error in strsplit(solver, "antares-")[[1]] : subscript out of bounds
```

**Comment by MarionLi0** [comment]
Erreur corrigée de mon côté, merci!
Message à changer à la fin: 
> Study ready for flow-based simulations

**Comment by TitouanRobert** [comment]
2 questions pour @baptsegu : 
Comment tester que le dossier de user/... ne correspond pas à l'output visualisé?
Quand tu as lancé initFlowBased(), qu'a tu dans antaresFlowbased::fbOptions()$path?

**Comment by baptsegu** [comment]
`"D:/Program Files/R/R-3.4.3/library/antaresFlowbased/input/model/model2017"`

**Comment by TitouanRobert** [comment]
Et dans getSolverAntares()?

**Comment by baptsegu** [comment]
```
getSolverAntares() 
NULL
```

**Comment by TitouanRobert** [comment]
Du coup il faut lui spécifier le solver chez moi : 
setSolverAntares("D:/Users/titorobe/Desktop/RTAANTARES/bin/antares-6.1-solver.exe")
Autrement tu peux le lancer avec controlAntares = FALSE (il faut qu'on discute de ce paramètres avec toi, je l'ai ajouté et nous voulions ton avis)

**Comment by baptsegu** [comment]
Après discussion.

On supprime le contrôle de la version du solveur ANTARES (le `setSolverAntares()` n'est plus nécessaire pour lancer `initFlowBased()`).

A la place, on contrôle la version de l'étude ANTARES (dans le fichier study, version >= 610).

En conséquence, l'argument `controlAntares `peut être supprimé.

**Comment by TitouanRobert** [comment]
J'ai supprimé les fonctions en rapport avec le solver, setSolverAntares, getSolverAntares. J'ai aussi adapté les vignettes.

**Comment by baptsegu** [comment]
Testé approuvé
