### ISSUE TITLE
Ajouter fonction setNamesProbabilityMatrix()

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#43]
setNamesProbabilityMatrix("old name", "new name")

**Comment by TitouanRobert** [comment]
Fait

**Comment by baptsegu** [comment]
Ca marche, merci :)
Pourrais tu faire en sorte qu'on passe dedans dans les tests et clore.

**Comment by TitouanRobert** [comment]
Fait
