### ISSUE TITLE
API de visualisation

### ISSUE THREAD

**Issue by TitouanRobert** [rte-antares-rpackage/antaresFlowbased#44]
Sur la fonction positionViz :

Sortir le chargement des données.
Permettre de visualiser plusieurs domaines sur un même graphique.
Faire une appli shiny qui reprend les paramètres de cette fonction pour faire le plot
Regarder comment s'exportent les données.

**Comment by TitouanRobert** [comment]
Voir la fonction : runAppPosition

**Comment by MarionLi0** [comment]
Donner une valeur par défaut à opts, actuellement il faut charger opts séparément (setSimulationPath) et ensuite lancer runAppPosition avec opts = opts dans les paramètres

**Comment by MarionLi0** [comment]
Ajouter la possibilité de choisir all pour les jours types et les heures

**Comment by MarionLi0** [comment]
Bug sur le range, si je mets la même date aux extrêmités (=je veux un jour spécifique), rien ne s'affiche, mais j'ai mes points si je mets le 1/07 et le 2/07 par exemple. Problème car je ne sais pas quel est le jour que je suis en train de regarder

**Comment by MarionLi0** [comment]
Fonction/application: le manque d'information sur les mcYear est problématique sur le graphe

**Comment by TitouanRobert** [comment]
Pour les 2 premières demandes c'est bon, pour l'affichage dans les tooltips cela concerne plus le plot je ré-ouvre une issue

**Comment by MarionLi0** [comment]
![image](https://user-images.githubusercontent.com/24607174/37203186-2350dc10-238d-11e8-92db-c89e0e680086.png)
Ce n'est pas réglé pour moi... 
Pareil pour les all ce n'est pas possible, oubli de commit?:)

**Comment by TitouanRobert** [comment]
Tu est bien sur la branche devADQ?

**Comment by MarionLi0** [comment]
Net positions before adequacy patch,
Net positions after adequacy patch

**Comment by MarionLi0** [comment]
Légende des graphes:
Day X - Hour Y

**Comment by MarionLi0** [comment]
Titre de la page: Flow-Based domains and CWE Net Positions

**Comment by MarionLi0** [comment]
Ecrire dans la bulle Hours
Hour h equals time step [h ; h+1]

**Comment by TitouanRobert** [comment]
@MarionLi0 Pour le bug d’affichage des checkbox normalement une mise à jour de shiny devrait solutionner le problème.

**Comment by TitouanRobert** [comment]
Je n'ai pas fait 

Légende des graphes:
Day X - Hour Y

Je le bouge dans l'issue sur les graphiques, pour le reste c'est bon.

**Comment by MarionLi0** [comment]
![image](https://user-images.githubusercontent.com/24607174/37279166-40f083f6-25ea-11e8-80ec-f278cc6448c2.png)
Alors il manque:
- le titre
- un NA s'est ajouté dans le titre des graphes

**Comment by TitouanRobert** [comment]
Fait

**Comment by MarionLi0** [comment]
Petit détail, le jaune est très dur à lire en particulier quand on cherche à retrouver des points avant et après adq, est ce possible de le retirer des couleurs?

**Comment by TitouanRobert** [comment]
https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf

Pour le moment j'ai pris la palette topo.colors (dernière page, section "colorRamps and grDevices")

Soit on fixe une palette de couleur sans jaune, soit on ajout un paramètre au plot, qu'en penses-tu?

**Comment by MarionLi0** [comment]
rainbow comme palette? Il y a nettement moins de jaune.
On peut imaginer rajouter un argument, défaut à rainbow

**Comment by TitouanRobert** [comment]
Ajout de l'échelle de couleur pour l'appli.

**Comment by MarionLi0** [comment]
Parfait pour l'appli!
