### ISSUE TITLE
ADQ, ajouter une fonction pour appliquer le traitement en H5

### ISSUE THREAD

**Issue by TitouanRobert** [rte-antares-rpackage/antaresFlowbased#47]
Un point important à voir ensemble, l'application de l'ADQ nécessite les fichiers : 
second_member.txt
scenario.txt
ts.txt
weight.txt

Ces fichiers ne sont pas présent actuellement dans une étude H5, pour réaliser le traitement il faut modifier la fonction writeAntaresH5 (package antaresRead).

Une fois les données nécessaires écrites, 2 options sont possibles : 

Option 1 :
Considérer la fonction adqPatch comme un enrichissement et l'intégrer à antaresProcessing de la même façon que addNetLoad, addDownwardMargin ..... Ensuite ajouté à la fonction addProcessingH5 plusieurs arguments pour pouvoir gérer l'enrichissement ADQ.

Option 2 :
Considérer l'ADQ comme à part, lui créer sa propre fonction d'enrichissement et son propre writeH5Adq.

De mon côté je suis plutôt favorable à la seconde option, nous sommes ici en présence d'un traitement spécifique et uniquement applicable à une étude de type flow-based (ce qui n'est pas le cas des autres traitements d'antareProcessing). De plus l'options 1 risque de verrouiller nos choix techniques et de rendre le code plus difficile à faire évoluer.

**Comment by MarionLi0** [comment]
A priori plutôt deuxième otion, je reviens sur ce que je t'ai dit hier, on ne complique pas tout en rendant les résultats traitables par antaresProcessing
