### ISSUE TITLE
New function/Update fonction? : Plot the FB domain of a specific time

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#48]
Fonction permettant d'afficher un domaine FB à partir de sa date/timeId et mc Year.
La fonction irait chercher à partir de la date le domaine type utilisé par Antares dans la simulation et afficherait : le domaine + la position nette dans CWE + (en option)position nette après adq

**Comment by TitouanRobert** [comment]
Comme vu ensemble,

On modifie la fonction positionViz avec 3 changements,

l'ajout de l’argument nbPtMax qui contrôle le nombre de points maximum traçable sur le graphique

L'ajout de l'argument filteringEmptyDomains Pour filtrer les domaines vides

La possibilité de mettre all ans les arguments dayType et hour.

+ ajouts d'exemple et doc pour montrer les 2 moyens d'utiliser la fonction

**Comment by MarionLi0** [comment]
Bug si je sélectionne seulement une heure dans mon dta, erreur à clarifier
![image](https://user-images.githubusercontent.com/24607174/37354768-b4ea1a44-26e2-11e8-81b8-a66f646f922f.png)

**Comment by MarionLi0** [comment]
Ok
