### ISSUE TITLE
Cohérence output/config FB dans l'étude Antares

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#49]
1. initFB
Ajouter à cette fonction l'écriture d'un fichier (titre du type 'info...') contenant l'heure d'écriture des binding constraints dans l'étude (dossier user)
2. A chaque appel de fichiers dans le dossier User (ex: adqPatch)
- Lire l'heure de l'output
- Comparer cette heure à l'heure du dossier User
- si heure_output < heure_initFB , renvoyer un warning -> comme les autres packages?

**Comment by MarionLi0** [comment]
Ajout du nom du modèle sous la date? (=nom du modèle si modèle du package ou nom du dossier si chemin perso)? @baptsegu

**Comment by baptsegu** [comment]
ok

**Comment by MarionLi0** [comment]
Ajouter le nom du modèle dans le fichier ini pour remplacer le test de vérification difficile en h5

**Comment by TitouanRobert** [comment]
J'ai du mal à comprendre comment faire ce test. Initialement nous voulions comparer la cohérence des outputs avec le dossier user. Nous nous référions donc à l'heure (écrite automatiquement dans le dossier output). Je peux écrire le nom du modèle dans le dossier user mais cela ne permet pas de vérifier la cohérence avec les outputs (ou il est impossible de renseigner un nom de modèle)

**Comment by MarionLi0** [comment]
C'est bon pour moi, pourrais tu enrichir la doc (partie Notes) pour préciser l'ajout de ce fichier avec la date et le modèle?
Détail, il y a un problème d'espace dans la description
![image](https://user-images.githubusercontent.com/24607174/37357156-f3060c52-26e7-11e8-8bfd-38d974767849.png)

**Comment by TitouanRobert** [comment]
Fait
