### ISSUE TITLE
RunSimulation : propositions d'évolution des logs

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#5]
Avoir deux niveaux de logs, du type :
- verbose = 0 (ne rien afficher)
- verbose = 1 (par défaut, équivalent de silent = FALSE)
- verbose = 2 (tout afficher)

Changer "staying" par "remaning"

Ajouter barre de progression pour suivre l'évolution des simus ANTARES (comme dans antaresRead - géré par plyr)

Ajouter infos dans la console sur l’agrégation.

**Comment by TitouanRobert** [comment]
C'est fais pour les logs tu peux tester.
