### ISSUE TITLE
Function merge output et TS file

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/antaresFlowbased#50]
Nom : addColumnTypicalDay ??
Arguments : antares data list, opts

Vérifier la cohérence heure output et initFB
Ajouter la colonne 'FBTypicalDay'

@baptsegu qu'en penses tu?

**Comment by TitouanRobert** [comment]
Un soucis les dates dans le ts.txt et celles de la simulation n'ont pas l'air de correspondre à tous les coup. Devons-nous plutôt merger par position du jour dans l'année plutôt que part date?

**Comment by MarionLi0** [comment]
C'est vrai, les années ne vont jamais correspondre! Est ce possible de ne vérifier que la partie de la date correspondant à mois-jour-date?
En gros la position marche si le jour de départ est le même..

**Comment by TitouanRobert** [comment]
J'ai conservé la partie jour-mois de la date et j'ai merge avec ça. J'ai un doute sur la gestion des années bissextiles.

**Comment by baptsegu** [comment]
addTypicalDayId

**Comment by TitouanRobert** [comment]
Fait

**Comment by MarionLi0** [comment]
Validé!
