### ISSUE TITLE
adqPatch : return Balance CWE

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#58]
``adqPatch()`` : ajouter les colonnes ``BALANCE_CWE`` et ``BALANCE_CWE_ADQPatch``

Pour avis @MarionLi0

**Comment by MarionLi0** [comment]
I agree

**Comment by baptsegu** [comment]
Pour Titouan : 
BALANCE_CWE = net position

Par exemple : 
BALANCE_CWE[fr] = - (fr%be) - (fr%de)

**Comment by TitouanRobert** [comment]
Je vous propose à la place une fonction : 

addNetPosition

En argument : 
data
opts
inScop (avec par défaut inScop =  c("be", "de", "fr", "nl"))
ADQ (par defaut FALSE)

C'est plus simple de mon côté de faire une fonction générique (qui va automatiquement chercher les liens concernés dans la zone et qui calcul les PNs). 
Au niveau perf c'est quasiment instantané (on peut tout faire en data.table)

**Comment by TitouanRobert** [comment]
Comme vu ensemble pour la V1 : 
Nom de la fonction addNetPosition
Arguments : 
data
opts
inAreas
ADQ
newName


Pour les tests : 
Vérification que giveIpn(data$links) (fonction de test de Marion) et addNetPosition(data) donne les mêmes résultats sur la zone CWE.

**Comment by MarionLi0** [comment]
adq miniscule

**Comment by MarionLi0** [comment]
test que tu peux ajouter s'il n'existe pas déjà: à chaque pas de temps (timeId, mcYear), la somme des net positions doit être égale à 0
