### ISSUE TITLE
plotNetPositionFB

### ISSUE THREAD

**Issue by TitouanRobert** [rte-antares-rpackage/antaresFlowbased#59]
Ajouter dans les tooltips des plots des infos (timeID, heure, ....)

**Comment by MarionLi0** [comment]
mcYear, mois+jour+heure

**Comment by TitouanRobert** [comment]
Légende des graphes:
Day X - Hour Y

**Comment by TitouanRobert** [comment]
Proposition d'ajout d'argument : columnToAddInTooltips ?

Qu'en pensez-vous @MarionLi0 @baptsegu ? (si on a le temps)

**Comment by baptsegu** [comment]
je ne comprends pas ce que fait ce nouvel argument

**Comment by TitouanRobert** [comment]
Il permettrait de spécifier des colonnes à ajouter dans les tooltips, pour le moment on a les IPN des 2 pays concernés, la date et l'heure ou peut aussi ajouter des colonnes choisies par l'utilisateur?

**Comment by TitouanRobert** [comment]
Il ajouterait aussi ces colonnes aux données en sortie

**Comment by MarionLi0** [comment]
Une nouvelle issue facultative a été créée pour ce nouvel argument #61 
ok pour le reste

**Comment by MarionLi0** [comment]
![image](https://user-images.githubusercontent.com/24607174/37412408-230c7f4a-27a5-11e8-8713-61097a73837c.png)
Partiellement corrigé...

**Comment by TitouanRobert** [comment]
C'est bon

**Comment by MarionLi0** [comment]
Parfait
