### ISSUE TITLE
Construction du mc-all : chiffres significatifs

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#6]
Dans la reconstruction du mc-all, les indicateurs de LOLD (exp, std, min et max) doivent être donnés avec deux chiffres après la virgule.

Idem pour la LOLP.

**Comment by TitouanRobert** [comment]
C'est modifié,

**Comment by baptsegu** [comment]
J'ai l'impression qu'on a de nouveau des arrondis à l'entier pour LOLD et LOLP.

**Comment by TitouanRobert** [comment]
J'ai passé le nombre de chiffres significatif de 0 à 2 pour LOLD. Pour LOLP j'ai déjà 2 chiffres significatifs (testé avec une étude sur 3 années 33.33%)
