### ISSUE TITLE
runSimulationFB : retourner des erreurs clairs lorsque les données stockées dans le user/flowbased/ sont incohérentes

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/antaresFlowbased#9]
Lorsqu'il y a plus de scenarios que d'années MC : 
i.e. size(scenario.txt) opts$parameters$general$nbyears

Lorsque scenario.txt contient des identifiants de time series qui n'existent pas

Lorsque ts.txt contient des identifiants de jour type qui n'existent pas

Lorsque second_member.txt n'est pas complet (i.e. le second membre n'est pas définit pour tous les jours types/heures/contraintes).

**Comment by TitouanRobert** [comment]
J'ai ajouté celui dont nous avons parlé vendredi
